### ISSUE TITLE
Game runs at 59 FPS instead of 60 and feels sligthly "stuttery"

### ISSUE THREAD

**Issue by Reonu** [PARTYMANX/partymod-thps3#10]
I don't think the 60 FPS framerate cap is working as intended. According to RTSS, it's running at 59 FPS, and the frametimes are variable, around the 16ms to 17ms range. The game feels slightly "stuttery" as a result, not as smooth as on my original Xbox for example, the frame pacing is not correct. 

I don't know if this is related to the mod or not, but regardless, it would be cool if this mod also fixed this issue.

Running on a 3070, with a 144 Hz monitor.

Thanks!

**Comment by PARTYMANX** [comment]
I'm using the original framerate limiting logic (though i've always been somewhat skeptical because the 60hz option doesn't seem to do anything), but i've also noticed that on my capture setup it often exhibits screen tearing.  Are you using windowed mode?  maybe it's the framerate logic clashing with vsync.  maybe check out how it performs with your refresh rate set to 60 or 120hz, my first thought is that maybe this is down to 144hz not cleanly dividing down to 60hz.

**Comment by Reonu** [comment]
No, I'm using fullscreen. Dropping my refresh rate to 60 Hz does not fix the issue, and that's unrelated anyways, if the game's FPS cap was working properly it would lock at 60 FPS properly. Whether those 60 FPS displayed at an even pace on my monitor would depend on whether my monitor has variable refresh rate support, which mine does. But the game is not capping itself properly, the frames are not being rendered at a correct pace to begin with, so they cannot be displayed at a correct pace on any display. (it's not even a constant 59 FPS. If it was, since my monitor has VRR, it would simply drop to 59 Hz automatically and deal with it. But the frametimes are not constant)

I never really thought your mod was causing the issue tbh. I was just wondering if you could look into having your mod fix it, on top of the other things it already fixes with the game.

Your capture setup having screen tearing is further proof that the framerate cap is broken. It should be a constant 16.6ms. Never a ms over, never a ms under. If it varies at all, the framerate cap is broken.

**Comment by Reonu** [comment]
Honestly, if coding a proper FPS cap is too big of a request, an option to disable the game's FPS cap entirely would do the trick. Because then I could cap it via other means (nvidia control panel, RTSS, whatever) and it should work properly. Right now setting an external cap does nothing because the game's FPS cap takes priority.

**Comment by PARTYMANX** [comment]
It's no issue to fix the limiter, I've done the same for THPS4 where the limiter was even more broken.  

I did run it through presentmon to get some data and I can confirm I'm getting 58.8fps average (exactly 17ms frame time.  what are the chances that they rely on 1ms sleeps exclusively?), so it's definitely just broken from the start.  

Thinking about it more, I think my tearing issue is only somewhat related.  My guess right now is that my display is displaying a partial frame on every other real frame (display is 120hz, game is just under 60) and vsync is not enabled.

Either way, I'll be fixing that when I get the chance.

**Comment by Reonu** [comment]
Alright, will wait for the fix, thank you :)

**Comment by PARTYMANX** [comment]
Alright, a patch is out now.  

I'm not actually sure what was causing the original issue.  the code seemed to check out but I'm not going to go back in to figure it out when I can just reimplement it.  I guess Gearbox didn't really think about laptop users back in 2001 because the mechanism was just a busywait.  My patch drastically reduces cpu usage because it makes use of sleeps until it gets to a certain threshold. 

I was curious to know how other games in the series handled their framerate caps just to make sure I was doing it properly, it seems like my solution is the most cpu friendly (THUG and on use 0ms sleeps which is only slightly better than a plain busywait), otherwise the setup is the same for the rest of the series.

I also corrected tearing by switching the swapchain swap effect to D3DSWAPEFFECT_COPY_VSYNC.

**Comment by Reonu** [comment]
It's MUCH better now, although still not a perfectly constant 16.6ms (there are still minor frame pacing variations). However, unlike before, setting a 60 FPS on RTSS now works and THEN it becomes a perfect 16.6ms. So all is well now, for me at least. Thanks :)
