### ISSUE TITLE
Holding the button for more than 1 frame when selecting "view goals list" dismisses the list instantly

### ISSUE THREAD

**Issue by Reonu** [PARTYMANX/partymod-thps3#11]
https://github.com/PARTYMANX/partymod-thps3/assets/15913880/e142a611-9448-4f7d-b15a-f1fb69f5012e

Not sure if this was an issue in the original game or not but it made me think it was straight up impossible to check the goal list until I realised what was happening. lol

**Comment by PARTYMANX** [comment]
Good find!  It's present in the original PC version, I don't have any other release of the game in a convenient spot for me to check if that happens in those versions, but I'd bet not.  either way it should probably be fixed.  wonder if it's a script change or something else

**Comment by Reonu** [comment]
You're not gonna believe this: I just tested the Xbox and GameCube versions and the issue happens in both of them as well. lol

However it's way less noticeable on console because the menu takes a bit to load, unlike on PC where it shows up immediately. So the player has most likely let go of the button by the time the menu shows up. On PC it's so fast that you won't let go of the button fast enough unless you're aware of the issue.

should be fixed either way like you said though yeah, extremely dumb issue

**Comment by PARTYMANX** [comment]
lmao that rocks

**Comment by PARTYMANX** [comment]
I ended up investigating this yesterday. I tried fixing the script to debounce the X button and it turns out that it doesn't fix the issue. Might be an issue somewhere else. That said, I did just get another idea to look into that I'll try out later. Maybe the script launching the screen isn't debouncing the X button...
